export interface ChainInfo {
  id: string;
  chainId: number;
  name: string;
  shortName: string;
  symbol: string;
  decimals: number;
  iconColor: string;
  bgActive: string;
  rpcUrls: string[];
  blockExplorer: string;
  disperseContract?: string;
  testnet?: boolean;
}

export const EVM_CHAINS: ChainInfo[] = [
  {
    id: "ethereum",
    chainId: 1,
    name: "Ethereum",
    shortName: "ETH",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#627EEA",
    bgActive: "bg-[#627EEA]/15 text-[#627EEA] border-[#627EEA]/40",
    rpcUrls: [
      "https://eth.llamarpc.com",
      "https://rpc.ankr.com/eth",
      "https://cloudflare-eth.com",
      "https://ethereum-rpc.publicnode.com",
    ],
    blockExplorer: "https://etherscan.io",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "arbitrum",
    chainId: 42161,
    name: "Arbitrum One",
    shortName: "ARB",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#28A0F0",
    bgActive: "bg-[#28A0F0]/15 text-[#28A0F0] border-[#28A0F0]/40",
    rpcUrls: [
      "https://arb1.arbitrum.io/rpc",
      "https://arbitrum.llamarpc.com",
      "https://arbitrum-one-rpc.publicnode.com",
    ],
    blockExplorer: "https://arbiscan.io",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "optimism",
    chainId: 10,
    name: "Optimism",
    shortName: "OP",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#FF0420",
    bgActive: "bg-[#FF0420]/15 text-[#FF0420] border-[#FF0420]/40",
    rpcUrls: [
      "https://mainnet.optimism.io",
      "https://optimism.llamarpc.com",
      "https://optimism-rpc.publicnode.com",
    ],
    blockExplorer: "https://optimistic.etherscan.io",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "apechain",
    chainId: 33139,
    name: "ApeChain",
    shortName: "APE",
    symbol: "APE",
    decimals: 18,
    iconColor: "#0054FA",
    bgActive: "bg-[#0054FA]/15 text-[#0054FA] border-[#0054FA]/40",
    rpcUrls: ["https://rpc.apechain.com", "https://apechain.calderachain.xyz/http"],
    blockExplorer: "https://apescan.io",
  },
  {
    id: "avalanche",
    chainId: 43114,
    name: "Avalanche C-Chain",
    shortName: "AVAX",
    symbol: "AVAX",
    decimals: 18,
    iconColor: "#E84142",
    bgActive: "bg-[#E84142]/15 text-[#E84142] border-[#E84142]/40",
    rpcUrls: ["https://api.avax.network/ext/bc/C/rpc", "https://avalanche.public-rpc.com"],
    blockExplorer: "https://snowtrace.io",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "base",
    chainId: 8453,
    name: "Base",
    shortName: "BASE",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#0052FF",
    bgActive: "bg-[#0052FF]/15 text-[#0052FF] border-[#0052FF]/40",
    rpcUrls: [
      "https://mainnet.base.org",
      "https://base.llamarpc.com",
      "https://base-rpc.publicnode.com",
    ],
    blockExplorer: "https://basescan.org",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "polygon",
    chainId: 137,
    name: "Polygon",
    shortName: "POL",
    symbol: "POL",
    decimals: 18,
    iconColor: "#8247E5",
    bgActive: "bg-[#8247E5]/15 text-[#8247E5] border-[#8247E5]/40",
    rpcUrls: [
      "https://polygon-rpc.com",
      "https://polygon.llamarpc.com",
      "https://polygon-bor-rpc.publicnode.com",
    ],
    blockExplorer: "https://polygonscan.com",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "berachain",
    chainId: 80094,
    name: "Berachain",
    shortName: "BERA",
    symbol: "BERA",
    decimals: 18,
    iconColor: "#8F5E36",
    bgActive: "bg-[#8F5E36]/15 text-[#8F5E36] border-[#8F5E36]/40",
    rpcUrls: ["https://rpc.berachain.com", "https://berachain-rpc.publicnode.com"],
    blockExplorer: "https://berascan.com",
  },
  {
    id: "bsc",
    chainId: 56,
    name: "BNB Smart Chain",
    shortName: "BSC",
    symbol: "BNB",
    decimals: 18,
    iconColor: "#F0B90B",
    bgActive: "bg-[#F0B90B]/15 text-[#F0B90B] border-[#F0B90B]/40",
    rpcUrls: [
      "https://binance.llamarpc.com",
      "https://bsc-rpc.publicnode.com",
      "https://rpc.ankr.com/bsc",
    ],
    blockExplorer: "https://bscscan.com",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "blast",
    chainId: 81457,
    name: "Blast",
    shortName: "BLAST",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#FCFC03",
    bgActive: "bg-[#FCFC03]/15 text-[#FCFC03] border-[#FCFC03]/40",
    rpcUrls: [
      "https://rpc.blast.io",
      "https://blast.blockpi.network/v1/rpc/public",
      "https://blast-rpc.publicnode.com",
    ],
    blockExplorer: "https://blastscan.io",
    disperseContract: "0xD152f549545093347A162Dce210e7293f1452150",
  },
  {
    id: "sei",
    chainId: 1329,
    name: "Sei Network",
    shortName: "SEI",
    symbol: "SEI",
    decimals: 18,
    iconColor: "#9B1C2E",
    bgActive: "bg-[#9B1C2E]/15 text-[#9B1C2E] border-[#9B1C2E]/40",
    rpcUrls: ["https://evm-rpc.sei-apis.com"],
    blockExplorer: "https://seitrace.com",
  },
  {
    id: "mode",
    chainId: 34443,
    name: "Mode Network",
    shortName: "MODE",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#DFFE00",
    bgActive: "bg-[#DFFE00]/15 text-[#DFFE00] border-[#DFFE00]/40",
    rpcUrls: ["https://mainnet.mode.network"],
    blockExplorer: "https://explorer.mode.network",
  },
  {
    id: "linea",
    chainId: 59144,
    name: "Linea",
    shortName: "LINEA",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#121212",
    bgActive: "bg-primary/15 text-primary border-primary/40",
    rpcUrls: ["https://rpc.linea.build", "https://linea.blockpi.network/v1/rpc/public"],
    blockExplorer: "https://lineascan.build",
  },
  {
    id: "scroll",
    chainId: 534352,
    name: "Scroll",
    shortName: "SCROLL",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#FFE7B9",
    bgActive: "bg-[#FFE7B9]/20 text-[#FFE7B9] border-[#FFE7B9]/40",
    rpcUrls: ["https://rpc.scroll.io", "https://scroll.blockpi.network/v1/rpc/public"],
    blockExplorer: "https://scrollscan.com",
  },
  {
    id: "mantle",
    chainId: 5000,
    name: "Mantle",
    shortName: "MNT",
    symbol: "MNT",
    decimals: 18,
    iconColor: "#000000",
    bgActive: "bg-primary/15 text-primary border-primary/40",
    rpcUrls: ["https://rpc.mantle.xyz"],
    blockExplorer: "https://mantlescan.xyz",
  },
  {
    id: "zora",
    chainId: 7777777,
    name: "Zora",
    shortName: "ZORA",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#000000",
    bgActive: "bg-primary/15 text-primary border-primary/40",
    rpcUrls: ["https://rpc.zora.energy"],
    blockExplorer: "https://explorer.zora.energy",
  },
  {
    id: "ink",
    chainId: 57073,
    name: "Ink",
    shortName: "INK",
    symbol: "ETH",
    decimals: 18,
    iconColor: "#9A00FF",
    bgActive: "bg-[#9A00FF]/15 text-[#9A00FF] border-[#9A00FF]/40",
    rpcUrls: ["https://rpc-gel.inkonchain.com"],
    blockExplorer: "https://explorer.inkonchain.com",
  },
  {
    id: "monad",
    chainId: 10143,
    name: "Monad",
    shortName: "MONAD",
    symbol: "MON",
    decimals: 18,
    iconColor: "#836EF9",
    bgActive: "bg-[#836EF9]/15 text-[#836EF9] border-[#836EF9]/40",
    rpcUrls: ["https://testnet-rpc.monad.xyz"],
    blockExplorer: "https://testnet.monadexplorer.com",
    testnet: true,
  },
];

export function getChainById(id: string): ChainInfo {
  return EVM_CHAINS.find((c) => c.id === id) || EVM_CHAINS[0];
}

export function getChainByChainId(chainId: number): ChainInfo {
  return EVM_CHAINS.find((c) => c.chainId === chainId) || EVM_CHAINS[0];
}
